[package]
name = "butt"
version = "0.1.2"
edition = "2024"
description = "Throttled tail/stdin monitor with regex highlighting"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
regex = "1.11.1"

[dev-dependencies]
tempfile = "3.13.0"
